---
apiVersion: v1
kind: Secret
metadata:
  name: ${JOB_NAME}
  namespace: ${namespace}
  labels:
    app: ${JOB_NAME}
type: Opaque
stringData:
  DB_URI: "mongodb://mongodb.db:27017/Samp_data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${JOB_NAME}
  namespace: ${namespace}
  labels:
    app: ${JOB_NAME}
spec:
  selector:
    matchLabels:
      app: ${JOB_NAME}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ${JOB_NAME}
    spec:
      terminationGracePeriodSeconds: 10
      hostname: ${JOB_NAME}
      containers:
      - name: ${JOB_NAME}
        image: ${ACR_NAME}/$JOB_NAME:$BUILD_NUMBER
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 7500
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: ${JOB_NAME}
              key: DB_URI
        readinessProbe:
          httpGet:
            path: /
            port: 7500
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 7500
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ${JOB_NAME}
  namespace: ${namespace}
  labels:
    app: ${JOB_NAME}
spec:
  selector:
    app: ${JOB_NAME}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7500
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ${JOB_NAME}
  namespace: ${namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${JOB_NAME}
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 180
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 180
